[tool.black]
line-length = 100
target-version = ["py313"]

[tool.ruff]
line-length = 100
target-version = "py313"
select = ["E", "F", "I"]
ignore = []
exclude = [
  "frontend/",
  "**/node_modules/**",
  "**/build/**",
]